# shellcheck shell=bash
# WAF по сигнатурам вендоров в заголовках/cookie/страницах и по страницам блокировки,
# которые вернули пробы WAF и тел устройств ($FPD/post*.b, $FPD/atk*.b).

WAFS=()
w() { # имя, regex по заголовкам, [regex по телу]
  if grep -Eq "$2" <<<"$ALLH"; then WAFS+=("$1")
  elif [[ -n "${3:-}" ]] && grep -Eq "$3" <<<"$ALLB"; then WAFS+=("$1"); fi
}
w "Cloudflare WAF"        '^server: cloudflare|^set-cookie: __cf_bm'
w "Akamai (Kona/Bot Mgr)" '^set-cookie: (ak_bmsc|bm_sz)|^x-akamai-'
w "Imperva / Incapsula"   '^x-iinfo:|^x-cdn: (imperva|incapsula)|^set-cookie: (incap_ses_|visid_incap_)'
w "F5 BIG-IP (ASM/AWAF)"  '^server: big-?ip|^set-cookie: (bigipserver|ts[0-9a-f]{8,})|^x-wa-info:'
w "AWS WAF"               '^x-amzn-waf-|^x-amzn-errortype:.*waf'
w "Sucuri"                '^x-sucuri-|^server: sucuri'
w "Fortinet FortiWeb"     '^set-cookie: (cookiesession1|fortiwafsid)'
w "Barracuda WAF"         '^set-cookie: (barra_counter_session|bni__barracuda)'
w "Citrix NetScaler AppFW" '^via: ns-cache|^set-cookie: (ns_af|citrix_ns_id|nsc_)'
w "ModSecurity"           '^server: .*mod_?security' 'mod_security|modsecurity|this error was generated by mod'
w "Wallarm"               '^server: nginx-wallarm|^x-wallarm'
w "Qrator"                '^server: qrator|^x-qrator'
w "DDoS-Guard"            '^server: ddos-guard|^set-cookie: __ddg[0-9]_'
w "Azure Front Door WAF"  '^x-azure-ref:'

BLK=$(cat "$FPD"/post*.b "$FPD"/atk*.b 2>/dev/null | head -c 20000 | tr -d '\0' | tr 'A-Z' 'a-z')
if grep -Eqi "$BLOCK_RE" <<<"$BLK"; then
  WAFS+=("не опознан по вендору (есть страница блокировки)")
  ids=$(cat "$FPD"/post*.b "$FPD"/atk*.b 2>/dev/null | grep -Eoi 'support id: *[0-9a-z-]+' | sed -E 's/^[^:]+: *//' | sort -u | head -3 | paste -sd, - | sed 's/,/, /g')
  [[ -n "$ids" ]] && printf "   • Support ID блокировок: %s%s%s\n" "$BD" "$ids" "$N"
fi
if (( ${#WAFS[@]} )); then
  printf "   • WAF (сигнатуры):     %s%s%s\n" "$Y$BD" "$(printf '%s, ' "${WAFS[@]}" | sed 's/, $//')" "$N"
else
  printf "   • WAF (сигнатуры):     %sв заголовках/cookie/страницах не найдены%s\n" "$D" "$N"
fi
